name: finance_app
description: "Aplicación de control de finanzas personales"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2
  
  # Base de datos - Drift (ORM)
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.1
  path: ^1.8.3
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Utilidades
  intl: ^0.19.0  # Formateo de fechas y números
  uuid: ^4.2.1   # Generar IDs únicos

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Code generation para Drift
  drift_dev: ^2.14.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  # assets:
  #   - images/
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf